### PR TITLE
fix typings

### PR DESCRIPTION
**Pull request by tommyxu**

### CODE REVIEW

**Comment by tommyxu** [comment]
node_modules/sleep-promise/build/cjs.d.ts:9:5 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

9     options: SleepOptions = {},
      ~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by tommyxu** [comment]
request to publish a new version if possible

**Comment by brummelte** [comment]
Thanks for this PR.

Could you please fix the `esm.d.ts` file aswell. Then I will merge this PR and publish a new version.

We probably should have some form of TypeScript tests, so that something like this doesn't happen in the future.

**Comment by KevinSnyderCodes** [comment]
This error shows up if you run:

```sh
tsc types/cjs.d.ts
# OR
tsc types/esm.d.ts
```

Running `tsc` could be a step in the CI process, if there is any.

Sorry for missing this. I don't compile TypeScript code in my project that uses `sleep-promise`, so I didn't notice any issues when using the latest version.

**Comment by brummelte** [comment]
Me neither 😉

Good that I published it as a major version upgrade.

I will add the TypeScript checks to the CI, thanks @KevinSnyderCodes.

**Comment by brummelte** [comment]
Ok I've fixed the esm file typings. Thanks @tommyxu and @KevinSnyderCodes.

Published as 8.0.0 now.

**Pull request merged**
